name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - name: List directory
        run: ls -A
